"""Structural domain-neutral environment interface; concrete schemas stay typed."""
from typing import Protocol, TypeVar, runtime_checkable
from mindscape.core.schema import Goal
ObservationT=TypeVar('ObservationT',contravariant=True)
StateT=TypeVar('StateT',covariant=True)
ActionT=TypeVar('ActionT')
TransitionT=TypeVar('TransitionT',covariant=True)
TrajectoryT=TypeVar('TrajectoryT',covariant=True)

@runtime_checkable
class Environment(Protocol[ObservationT,StateT,ActionT,TransitionT,TrajectoryT]):
    def reset(self, problem: ObservationT) -> StateT: ...
    def get_state(self) -> StateT: ...
    def get_goal(self) -> Goal: ...
    def valid_actions(self) -> tuple[ActionT, ...]: ...
    def step(self, action: ActionT) -> TransitionT: ...
    def is_goal_reached(self) -> bool: ...
    def get_trajectory(self) -> TrajectoryT: ...
