from typing import Protocol
from mindscape.core.schema import Action, Goal, State, Trajectory, Transition


class Environment(Protocol):
    def reset(self, problem: tuple[int, int]) -> State: ...
    def get_state(self) -> State: ...
    def get_goal(self) -> Goal: ...
    def valid_actions(self) -> tuple[Action, ...]: ...
    def step(self, action: Action) -> Transition: ...
    def is_goal_reached(self) -> bool: ...
    def get_trajectory(self) -> Trajectory: ...
