"""Static UI over first30 frozen IID examples; shows public structured evidence."""
import argparse,json
from pathlib import Path

def main():
 p=argparse.ArgumentParser();p.add_argument('results');p.add_argument('--output',default='demo/index.html');p.add_argument('--dataset',default='datasets/generated/final_v1');args=p.parse_args();root=Path(args.results);runs=[json.loads(x) for x in (root/'runs.jsonl').read_text().splitlines()]
 def load(c):
  r=next(r for r in runs if r['condition']==c and r['variant']=='full' and r['budget']==1000 and r['seed']==0 and r['split']=='test');return [json.loads(x) for x in (Path(r['directory'])/'predictions.jsonl').read_text().splitlines()][:30]
 from mindscape.data.generation import load_dataset
 s,_=load_dataset(args.dataset);byid={e.example_id:e for e in s['test']}
 a,b=load('answer_only'),load('trajectory')
 for r in a+b:r['problem']=byid[r['example_id']].problem
 dataset=[dict(baseline=x,mindscape=y) for x,y in zip(a,b)];payload=json.dumps(dataset).replace('<','\\u003c')
 html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Mindscape research evidence</title><style>body{font:16px system-ui;background:#f4f7fb;color:#14233b;margin:0}main{max-width:1050px;margin:40px auto;padding:24px}h1{font-size:30px}select,button{padding:10px;border:1px solid #bbc7d8;border-radius:8px;background:white}section{background:white;padding:20px;margin:16px 0;border-radius:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px;background:#f0f3f8;padding:14px}.row{display:flex;gap:18px;flex-wrap:wrap}.badge{font-weight:700}small{color:#526078}</style><main><h1>Mindscape: structured execution evidence</h1><p>Frozen research demonstration. First30 IID examples, budget1000, seed0. Outputs are measured predictions; incorrect actions remain visible.</p><div class="row"><label>Example <select id="example"></select></label><label>Condition <select id="mode"><option value="baseline">Answer-only baseline</option><option value="mindscape">Mindscape B</option></select></label></div><section id="summary"></section><section><div class="row"><button id="previous">Previous transition</button><button id="next">Next transition</button><span id="position"></span></div><div id="evidence"></div></section><small>Public state/action/event/result records only. Verifier judgments are post-evaluation annotations and were unavailable to the model. Baseline emits no execution evidence. SmolLM2 is frozen; task heads are learned. No superiority claim is implied.</small></main><script>const data=PAYLOAD;let step=0;const ex=document.querySelector('#example'),mode=document.querySelector('#mode');data.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(i+1)+'. '+r.baseline.problem;ex.append(o)});function show(){let r=data[+ex.value][mode.value];let summary=document.querySelector('#summary');summary.textContent='';for(let [k,v] of Object.entries({problem:r.problem,answer:r.predicted_answer,correct:r.correct,grounded:r.grounded,trajectory_valid:r.trajectory_valid,goal_reached:r.goal_reached})){let p=document.createElement('p');p.textContent=k+': '+JSON.stringify(v);summary.append(p)}let ds=r.diagnostics?.decisions||[];step=Math.max(0,Math.min(step,ds.length-1));document.querySelector('#position').textContent=ds.length?'Transition '+(step+1)+' / '+ds.length:'No trajectory emitted';let e=document.querySelector('#evidence');e.textContent='';let pre=document.createElement('pre');pre.textContent=ds.length?JSON.stringify(ds[step],null,2):'Answer-only output has no recorded state/action/event/result sequence.';e.append(pre)}ex.onchange=mode.onchange=()=>{step=0;show()};document.querySelector('#previous').onclick=()=>{step--;show()};document.querySelector('#next').onclick=()=>{step++;show()};show();</script></html>'''.replace('PAYLOAD',payload)
 out=Path(args.output);out.parent.mkdir(parents=True,exist_ok=True);out.write_text(html);print(out)
if __name__=='__main__':main()
